"""Baseline schema: the full v1 table set, as ``Base.metadata`` declares it.

Revision ID: 0001
Revises:
Create Date: 2026-09-25

AC-INFRA-1 says ``alembic upgrade head`` must be equivalent to
``Base.metadata.create_all()`` - and the direction that actually bites is the
existing install. Operators who deployed v1 with ``create_all()`` have the tables
but no ``alembic_version`` row, so every DDL statement below is guarded on
inspection: ``upgrade head`` on such a database converges (no-ops) instead of
failing on ``CREATE TABLE``, and stamping afterwards is optional.

Hand-written rather than autogenerated so column order, nullability and index
names stay reviewable. ``tests/test_migrations.py`` holds it to ``Base.metadata``
with ``compare_metadata`` *and* by comparing the emitted DDL to ``create_all()``.

Constraint names are deliberately not passed to the DDL ops: ``Base`` configures no
SQLAlchemy naming convention, so naming them here would be a schema claim the
metadata does not make.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Exactly what the models declare, so Postgres gets TIMESTAMP WITH TIME ZONE
#: instead of a silently naive column, and SQLite keeps its DATETIME affinity.
_TSTZ = sa.DateTime(timezone=True)


def _table_exists(name: str) -> bool:
    """Is the table already there?

    Offline mode (``upgrade head --sql``) connects to nothing, so there is nothing
    to inspect: it is treated as a new database and every statement is emitted.
    """
    if op.get_context().as_sql:
        return False
    return name in sa.inspect(op.get_bind()).get_table_names()


def _index_exists(table: str, name: str) -> bool:
    if op.get_context().as_sql:
        return False
    return name in {idx["name"] for idx in sa.inspect(op.get_bind()).get_indexes(table)}


def upgrade() -> None:
    if not _table_exists("api_keys"):
        op.create_table(
            "api_keys",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("key_id", sa.String(length=32), nullable=False),
            sa.Column("key_hash", sa.String(length=64), nullable=False),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("role", sa.String(length=20), nullable=False),
            sa.Column("organisation", sa.String(length=120), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("rate_limit_rpm", sa.Integer(), nullable=True),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.Column("last_used_at", _TSTZ, nullable=True),
            sa.Column("revoked_at", _TSTZ, nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=True)
        op.create_index("ix_api_keys_key_id", "api_keys", ["key_id"], unique=True)
        op.create_index("ix_api_keys_organisation", "api_keys", ["organisation"])

    if not _table_exists("media_assets"):
        op.create_table(
            "media_assets",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("sha256", sa.String(length=64), nullable=False),
            sa.Column("media_type", sa.String(length=20), nullable=False),
            sa.Column("filename", sa.String(length=255), nullable=False),
            sa.Column("mime_type", sa.String(length=120), nullable=False),
            sa.Column("size_bytes", sa.Integer(), nullable=False),
            sa.Column("storage_path", sa.String(length=512), nullable=False),
            sa.Column("external_uri", sa.String(length=1024), nullable=True),
            sa.Column("submitted_by", sa.String(length=64), nullable=True),
            sa.Column("organisation", sa.String(length=120), nullable=False),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_media_assets_created_at", "media_assets", ["created_at"])
        op.create_index("ix_media_assets_media_type", "media_assets", ["media_type"])
        op.create_index("ix_media_assets_sha256", "media_assets", ["sha256"])

    if not _table_exists("jobs"):
        op.create_table(
            "jobs",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("media_id", sa.String(length=32), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("priority", sa.Integer(), nullable=False),
            sa.Column("requested_detectors", sa.JSON(), nullable=True),
            sa.Column("risk_score", sa.Float(), nullable=True),
            sa.Column("risk_tier", sa.String(length=20), nullable=True),
            sa.Column("confidence", sa.Float(), nullable=True),
            sa.Column("detector_coverage", sa.Float(), nullable=True),
            sa.Column("result", sa.JSON(), nullable=True),
            sa.Column("error", sa.Text(), nullable=True),
            sa.Column("attempts", sa.Integer(), nullable=False),
            sa.Column("created_by", sa.String(length=64), nullable=True),
            sa.Column("organisation", sa.String(length=120), nullable=False),
            sa.Column("idempotency_key", sa.String(length=128), nullable=True),
            sa.Column("callback_url", sa.String(length=1024), nullable=True),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.Column("started_at", _TSTZ, nullable=True),
            sa.Column("finished_at", _TSTZ, nullable=True),
            sa.ForeignKeyConstraint(["media_id"], ["media_assets.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_jobs_created_at", "jobs", ["created_at"])
        op.create_index("ix_jobs_media_id", "jobs", ["media_id"])
        op.create_index("ix_jobs_organisation", "jobs", ["organisation"])
        op.create_index("ix_jobs_status", "jobs", ["status"])
        if not _index_exists("jobs", "ix_jobs_org_status"):
            op.create_index("ix_jobs_org_status", "jobs", ["organisation", "status"])

    if not _table_exists("webhook_endpoints"):
        op.create_table(
            "webhook_endpoints",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("url", sa.String(length=1024), nullable=False),
            sa.Column("secret", sa.String(length=128), nullable=False),
            sa.Column("organisation", sa.String(length=120), nullable=False),
            sa.Column("description", sa.String(length=255), nullable=False),
            sa.Column("events", sa.JSON(), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_webhook_endpoints_organisation", "webhook_endpoints", ["organisation"])

    if not _table_exists("webhook_deliveries"):
        op.create_table(
            "webhook_deliveries",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("webhook_id", sa.String(length=32), nullable=False),
            sa.Column("job_id", sa.String(length=32), nullable=True),
            sa.Column("event_type", sa.String(length=64), nullable=False),
            sa.Column("attempt", sa.Integer(), nullable=False),
            sa.Column("max_attempts", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("response_code", sa.Integer(), nullable=True),
            sa.Column("error", sa.Text(), nullable=True),
            sa.Column("next_attempt_at", _TSTZ, nullable=True),
            sa.Column("payload", sa.JSON(), nullable=True),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.Column("delivered_at", _TSTZ, nullable=True),
            sa.ForeignKeyConstraint(["webhook_id"], ["webhook_endpoints.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_webhook_deliveries_job_id", "webhook_deliveries", ["job_id"])
        op.create_index("ix_webhook_deliveries_status", "webhook_deliveries", ["status"])
        op.create_index("ix_webhook_deliveries_webhook_id", "webhook_deliveries", ["webhook_id"])

    if not _table_exists("policy_profiles"):
        op.create_table(
            "policy_profiles",
            sa.Column("id", sa.String(length=32), nullable=False),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("organisation", sa.String(length=120), nullable=False),
            sa.Column("description", sa.String(length=255), nullable=False),
            sa.Column("thresholds", sa.JSON(), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("created_at", _TSTZ, nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
        op.create_index("ix_policy_profiles_organisation", "policy_profiles", ["organisation"])

    if not _table_exists("audit_events"):
        op.create_table(
            "audit_events",
            sa.Column("seq", sa.Integer(), nullable=False),
            sa.Column("event_id", sa.String(length=32), nullable=False),
            sa.Column("actor", sa.String(length=120), nullable=False),
            sa.Column("action", sa.String(length=80), nullable=False),
            sa.Column("resource", sa.String(length=160), nullable=False),
            sa.Column("detail", sa.JSON(), nullable=True),
            sa.Column("prev_hash", sa.String(length=64), nullable=False),
            sa.Column("entry_hash", sa.String(length=64), nullable=False),
            sa.Column("ts", _TSTZ, nullable=False),
            sa.PrimaryKeyConstraint("seq"),
            sa.UniqueConstraint("event_id"),
        )
        op.create_index("ix_audit_events_action", "audit_events", ["action"])
        op.create_index("ix_audit_events_entry_hash", "audit_events", ["entry_hash"])
        op.create_index("ix_audit_events_ts", "audit_events", ["ts"])


def downgrade() -> None:
    for table in (
        "audit_events",
        "policy_profiles",
        "webhook_deliveries",
        "webhook_endpoints",
        "jobs",
        "media_assets",
        "api_keys",
    ):
        if _table_exists(table):
            op.drop_table(table)
